import { jsPDF } from "jspdf";


const COLORS = {
  primary: [16, 185, 129], 
  secondary: [5, 150, 105], 
  dark: [31, 41, 55],
  light: [107, 114, 128], 
  white: [255, 255, 255],
  success: [34, 197, 94],
  error: [239, 68, 68],
};


function addHeader(doc, title, subtitle = "") {
  const pageWidth = doc.internal.pageSize.getWidth();

 
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageWidth, 40, "F");

 
  doc.setTextColor(...COLORS.white);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("StudyAI", 20, 20);

 
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text(title, 20, 32);

  
  if (subtitle) {
    doc.setFontSize(10);
    doc.text(subtitle, pageWidth - 20, 32, { align: "right" });
  }

  return 50; 
}


function addFooter(doc, pageNum) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setFontSize(8);
  doc.setTextColor(...COLORS.light);
  doc.text(
    `Generated by StudyAI • ${new Date().toLocaleDateString()}`,
    20,
    pageHeight - 10
  );
  doc.text(`Page ${pageNum}`, pageWidth - 20, pageHeight - 10, {
    align: "right",
  });
}


function stripMarkdown(text) {
  return text
    .replace(/#{1,6}\s?/g, "")
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/\*(.+?)\*/g, "$1")
    .replace(/`(.+?)`/g, "$1")
    .replace(/```[\s\S]*?```/g, "")
    .replace(/\[(.+?)\]\(.+?\)/g, "$1")
    .replace(/[-*+]\s/g, "• ")
    .trim();
}


export function exportSummaryToPDF(summary, documentTitle = "Document") {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;

  let y = addHeader(doc, "Summary", documentTitle);
  let pageNum = 1;

 
  const plainText = stripMarkdown(summary);
  const lines = doc.splitTextToSize(plainText, maxWidth);

  doc.setTextColor(...COLORS.dark);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  lines.forEach((line) => {
    if (y > pageHeight - 30) {
      addFooter(doc, pageNum);
      doc.addPage();
      pageNum++;
      y = addHeader(doc, "Summary (continued)", documentTitle);
    }

    
    if (line.startsWith("•")) {
      doc.setFont("helvetica", "normal");
      doc.text(line, margin + 5, y);
    } else if (line.length < 50 && !line.includes(" ")) {
      doc.setFont("helvetica", "bold");
      doc.text(line, margin, y);
    } else {
      doc.setFont("helvetica", "normal");
      doc.text(line, margin, y);
    }

    y += 7;
  });

  addFooter(doc, pageNum);
  doc.save(`${documentTitle}_Summary.pdf`);
}


export function exportFlashcardsToPDF(flashcards, setName = "Flashcard Set") {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const cardWidth = pageWidth - margin * 2;
  const cardHeight = 60;

  let y = addHeader(doc, "Flashcards", `${flashcards.length} cards`);
  let pageNum = 1;

  flashcards.forEach((card, index) => {
    
    if (y + cardHeight + 20 > pageHeight - 30) {
      addFooter(doc, pageNum);
      doc.addPage();
      pageNum++;
      y = addHeader(doc, "Flashcards (continued)", `${flashcards.length} cards`);
    }

    
    doc.setFillColor(...COLORS.primary);
    doc.roundedRect(margin, y, 30, 10, 2, 2, "F");
    doc.setTextColor(...COLORS.white);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text(`Card ${index + 1}`, margin + 5, y + 7);

    y += 15;

    
    doc.setFillColor(240, 253, 244); 
    doc.roundedRect(margin, y, cardWidth, 25, 3, 3, "F");
    doc.setDrawColor(...COLORS.primary);
    doc.roundedRect(margin, y, cardWidth, 25, 3, 3, "S");

    doc.setTextColor(...COLORS.secondary);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("QUESTION", margin + 5, y + 8);

    doc.setTextColor(...COLORS.dark);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const questionLines = doc.splitTextToSize(card.question, cardWidth - 10);
    doc.text(questionLines.slice(0, 2).join(" "), margin + 5, y + 18);

    y += 30;

    
    doc.setFillColor(...COLORS.primary);
    doc.roundedRect(margin, y, cardWidth, 25, 3, 3, "F");

    doc.setTextColor(...COLORS.white);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("ANSWER", margin + 5, y + 8);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const answerLines = doc.splitTextToSize(card.answer, cardWidth - 10);
    doc.text(answerLines.slice(0, 2).join(" "), margin + 5, y + 18);

    y += 35;
  });

  addFooter(doc, pageNum);
  doc.save(`${setName}_Flashcards.pdf`);
}


export function exportQuizResultsToPDF(
  questions,
  score,
  total,
  quizTitle = "Quiz"
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;

  let y = addHeader(doc, "Quiz Results", quizTitle);
  let pageNum = 1;

  
  const percent = Math.round((score / total) * 100);
  const scoreColor = percent >= 70 ? COLORS.success : percent >= 50 ? [234, 179, 8] : COLORS.error;

  doc.setFillColor(249, 250, 251);
  doc.roundedRect(margin, y, maxWidth, 40, 5, 5, "F");
  doc.setDrawColor(...scoreColor);
  doc.setLineWidth(2);
  doc.roundedRect(margin, y, maxWidth, 40, 5, 5, "S");

  
  doc.setTextColor(...scoreColor);
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text(`${score}/${total}`, margin + 15, y + 25);

  doc.setFontSize(14);
  doc.text(`${percent}%`, margin + 60, y + 25);

  
  doc.setTextColor(...COLORS.dark);
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  const message =
    percent === 100
      ? "🏆 Perfect Score!"
      : percent >= 70
        ? "✓ Great job!"
        : percent >= 50
          ? "Good effort, keep practicing!"
          : "Review the material and try again.";
  doc.text(message, margin + 100, y + 25);

  y += 55;

  
  doc.setTextColor(...COLORS.dark);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Question Review", margin, y);
  y += 15;

  questions.forEach((q, index) => {
    const isCorrect = q.user_answer === q.correct_option;
    const questionHeight = 50;

    if (y + questionHeight > pageHeight - 30) {
      addFooter(doc, pageNum);
      doc.addPage();
      pageNum++;
      y = addHeader(doc, "Quiz Results (continued)", quizTitle);
    }

    
    doc.setFillColor(isCorrect ? 220 : 254, isCorrect ? 252 : 226, isCorrect ? 231 : 226);
    doc.roundedRect(margin, y, maxWidth, questionHeight, 3, 3, "F");

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    const statusColor = isCorrect ? COLORS.success : COLORS.error;
    doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
    doc.text(`Q${index + 1}. ${isCorrect ? "✓ Correct" : "✗ Incorrect"}`, margin + 5, y + 10);

    
    doc.setTextColor(...COLORS.dark);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const questionLines = doc.splitTextToSize(q.question, maxWidth - 10);
    doc.text(questionLines[0], margin + 5, y + 22);

    
    doc.setFontSize(9);
    const options = [q.option_a, q.option_b, q.option_c, q.option_d];
    const optionLabels = ["A", "B", "C", "D"];

    if (!isCorrect && q.user_answer !== null) {
      doc.setTextColor(...COLORS.error);
      doc.text(
        `Your answer: ${optionLabels[q.user_answer]}. ${options[q.user_answer] || ""}`,
        margin + 5,
        y + 34
      );
    }

    doc.setTextColor(...COLORS.success);
    doc.text(
      `Correct: ${optionLabels[q.correct_option]}. ${options[q.correct_option]}`,
      margin + 5,
      y + 44
    );

    y += questionHeight + 8;
  });

  addFooter(doc, pageNum);
  doc.save(`${quizTitle}_Results.pdf`);
}
